# Site settings
title: Exploreapollo.org Project
description: >
  Documentation for the exploreapollo.org project

# Build settings
markdown: kramdown
  
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
